Add data store and store window bounds
diracdeltas/signal-muon pull request #26
Opened 2017-03-12 10:40 UTC by mammuth

I added a generic store handler, which still stores production and dev settings in different files. It also can handle defaults.

Right now it's only used for storing the window bounds. Bounds are updated when the window is closed.

Are you fine with handling userData this way, @diracdeltas ?
There are no linting errors.

Fixes diracdeltas/signal-muon/issues/24

2017-03-13 07:22 UTC, diracdeltas commented on main.js
> -// use a separate data directory for development
This should be undeleted I think

2017-03-13 07:26 UTC, diracdeltas commented on main.js
> -// use a separate data directory for development
nevermind, i see where it is handled below

2017-03-13 07:27 UTC, diracdeltas commented on store.js
> +    // Use a different userData file for development
i think you still need to do app.setPath here; otherwise prod and dev will share the same app data directory.

2017-03-13 07:29 UTC, diracdeltas commented on store.js
> +    fs.writeFileSync(this.path, JSON.stringify(this.data))
no need to use writeFileSync instead of writeFile here

2017-03-13 07:31 UTC, diracdeltas commented
thanks for this! this seems like a reasonable approach, assuming that https://github.com/diracdeltas/signal-desktop isn't saving the window sizes. (If so, I would prefer to get them from the signal-desktop extension in order to avoid having an app data store at all.)

2017-03-13 14:28 UTC, mammuth commented
Thanks for the fast review. I changed the PR based on your comments.

2017-03-13 20:31 UTC, diracdeltas commented
please `git rebase -i` to squash commits into one commit. thanks!

2017-03-14 15:02 UTC, mammuth commented
Done. 
You're no big fan of using GitHub's shiny new button for Squashing and Merging directly from PR's?😉

2017-03-14 18:35 UTC, diracdeltas commented
@mammuth actually i forgot it existed. thanks for the reminder!

2017-03-14 18:37 UTC, diracdeltas requested changes

2017-03-14 18:37 UTC, diracdeltas commented on store.js
> +      app.setPath('userData', path.join(app.getPath('appData'), 'signal-muon'))
app is not defined here. i think it is better to put this where it was before in main.js. The path does not need to be set every time that a store is instantiated.

2017-03-14 18:37 UTC, diracdeltas commented on store.js
> +    const configName = isProduction ? opts.configName : opts.configName + '-dev'
it's unnecessary to use a different configName now that the appData directories are different

2017-03-14 18:37 UTC, diracdeltas commented on store.js
> +    const userDataPath = (electron.app || electron.remote.app).getPath('userData')
probably safe to assume for now that this will only get called in the main process

2017-03-16 17:11 UTC, diracdeltas commented
^ ping on requested changes

2017-03-17 18:57 UTC, mammuth commented
Wups, didn't notice that you requested new changes 😊 sorry for the delay.

2017-03-20 22:23 UTC, diracdeltas approved these changes

2017-03-20 22:27 UTC, merged