getting ncp with npm install
diracdeltas/signal-muon pull request #28
Opened 2017-03-14 14:13 UTC by asafonov

Setting ncp as a project dependency and use it in a build script. It's not a bad idea, isn't it?

2017-03-15 05:45 UTC, diracdeltas requested changes

2017-03-15 05:45 UTC, diracdeltas commented on package.json
> +  "dependencies": {
i think this should go in devDependencies instead of dependencies

2017-03-15 06:55 UTC, asafonov commented
@diracdeltas I completely agree with you. Updated

2017-03-15 18:33 UTC, diracdeltas commented
On second thought, it doesn't seem worth the effort to require `ncp` as a devDependency just for a single command where `cp -r` would work fine. Maybe just change it to `cp`?

2017-03-16 08:05 UTC, asafonov commented
@diracdeltas Yes, the less dependencies the better. I changed build script, but I can't test on Windows

2017-03-16 15:08 UTC, diracdeltas commented
thanks!

2017-03-16 15:08 UTC, diracdeltas approved these changes

2017-03-16 15:08 UTC, merged